import type { Phase } from "../types"

export const phase8: Phase = {
  numero: 8,
  titre: "Réception et clôture",
  intro:
    "La réception est l'acte par lequel le maître d'ouvrage accepte l'ouvrage, avec ou sans réserves : elle transfère la garde de l'ouvrage et fait courir toutes les garanties légales. C'est une décision du seul maître d'ouvrage, préparée par la maîtrise d'œuvre et éclairée par l'AMO. La phase se poursuit jusqu'au solde de tous les marchés, à l'expiration de la garantie de parfait achèvement et au retour d'expérience de l'opération.",
  etapes: [
    {
      code: "8.1",
      titre: "Opérations préalables à la réception",
      objectif: "Constater contradictoirement l'état de l'ouvrage, lot par lot, et dresser la liste exhaustive des réserves.",
      roles: [
        { acteur: "ENTREPRISES", role: "Avisent de l'achèvement et demandent la réception ; participent aux constats." },
        { acteur: "MOE", role: "Organise et conduit les opérations préalables, établit le procès-verbal (élément de mission AOR)." },
        { acteur: "OPC", role: "Planifie les opérations par lot et par zone, puis la levée des réserves." },
        { acteur: "AMO", role: "Participe pour le compte du maître d'ouvrage, veille à l'exhaustivité des constats et au respect des délais." },
        { acteur: "MOA", role: "Est convoqué ; peut participer aux visites." },
      ],
      entrees: ["Demande de réception des entreprises", "Résultats des essais", "Rapport final du contrôleur technique", "Planning de fin de chantier"],
      livrables: [
        "Grille de visite par lot et par local ou section d'ouvrage",
        "Relevé des écarts transmis à la maîtrise d'œuvre avant signature du procès-verbal",
      ],
      outil: [
        "Grille de visite générée depuis les lots et le profil de l'opération",
        "Saisie des réserves sur site (photo, localisation, lot, gravité)",
        "Pré-remplissage du procès-verbal des opérations préalables (formulaire EXE4)",
      ],
      humain: ["Visite contradictoire", "Qualification de chaque réserve : défaut d'exécution, non-conformité, inachèvement"],
      vigilance: [
        "Des essais non réalisés ou non concluants sont une réserve en soi.",
        "Les réserves doivent être précises (lieu, nature, lot responsable) : une réserve vague n'est pas levable.",
        "Respecter les délais du CCAG entre l'avis d'achèvement et les opérations préalables.",
      ],
      variantes: [
        { quand: { typologie: ["BATIMENT_ERP"] }, texte: "Coordonner avec la visite de la commission de sécurité, préalable à l'ouverture au public." },
        { quand: { typologie: ["OUVRAGE_ART"] }, texte: "Intégrer les résultats des épreuves de l'ouvrage aux constats.", aPreciser: true },
        { quand: { typologie: ["RESEAUX", "INFRA_LINEAIRE"] }, texte: "Exiger les essais d'étanchéité, de compactage et les inspections prévues au marché, ainsi que les plans de récolement." },
        { quand: { montage: ["MARCHE_PRIVE"] }, texte: "Pas de formulaire imposé : procès-verbal selon le contrat et, le cas échéant, la norme de marché privé visée." },
      ],
      textes: [
        "Code civil, art. 1792-6 (réception)",
        "CCAG Travaux 2021 (réception)",
        "Arrêté du 22 mars 2019 (annexe 20 du Code de la commande publique) : élément de mission AOR",
        "Formulaire DAJ EXE4",
      ],
      statut: "brouillon",
    },
    {
      code: "8.2",
      titre: "Décision de réception",
      objectif: "Permettre au maître d'ouvrage de prononcer, en connaissance de cause et dans les délais, la réception avec ou sans réserves, ou son refus.",
      roles: [
        { acteur: "MOE", role: "Propose au maître d'ouvrage de prononcer ou non la réception et fixe la date d'achèvement proposée." },
        { acteur: "AMO", role: "Analyse les propositions de la maîtrise d'œuvre et rédige un avis motivé au maître d'ouvrage." },
        { acteur: "MOA", role: "Décide et notifie la réception, avec ou sans réserves, ou la non-réception." },
      ],
      livrables: ["Avis motivé au maître d'ouvrage : recevoir, recevoir avec réserves, recevoir sous condition d'épreuves, refuser", "Projet de décision soumis à signature"],
      outil: [
        "Pré-remplissage des propositions de la maîtrise d'œuvre et de la décision (formulaires EXE5, EXE6 ou EXE7)",
        "Calcul automatique des échéances qui en découlent : fin de la garantie de parfait achèvement, de la garantie de bon fonctionnement, de la garantie décennale, libération des retenues",
      ],
      humain: ["Avis sur l'opportunité de recevoir", "Explication au maître d'ouvrage des conséquences de chaque option"],
      vigilance: [
        "La date de réception fait courir la garantie de parfait achèvement (un an), la garantie de bon fonctionnement (deux ans au moins) et la responsabilité décennale.",
        "Selon le CCAG, le silence du maître d'ouvrage après les propositions de la maîtrise d'œuvre peut valoir acceptation : ne jamais laisser courir le délai.",
        "Une prise de possession anticipée d'une partie de l'ouvrage doit être formalisée : elle a des effets sur la garde et les garanties.",
        "L'AMO ne prononce jamais la réception et ne signe aucun procès-verbal au nom du maître d'ouvrage.",
      ],
      variantes: [
        { quand: { montage: ["MOE_LOTS_SEPARES"] }, texte: "Une réception par lot est possible si le marché le prévoit ; veiller à la cohérence des dates entre lots interdépendants." },
        { quand: { montage: ["CONCEPTION_REALISATION", "MARCHE_GLOBAL"] }, texte: "Pas de maîtrise d'œuvre indépendante : l'AMO ou le conducteur d'opération instruit seul l'avis au maître d'ouvrage, d'où l'importance des constats contradictoires." },
        { quand: { montage: ["MARCHE_PARTENARIAT", "CONCESSION"] }, texte: "Le titulaire est maître d'ouvrage : la personne publique constate la mise à disposition selon les clauses du contrat, sans réception au sens du Code civil." },
        { quand: { typologie: ["FERROVIAIRE"] }, texte: "La réception ne vaut pas mise en service : celle-ci relève d'autorisations de sécurité propres au transport guidé.", aPreciser: true },
      ],
      textes: ["Code civil, art. 1792, 1792-3, 1792-6", "CCAG Travaux 2021 (réception)", "Formulaires DAJ EXE5, EXE6, EXE7"],
      statut: "brouillon",
    },
    {
      code: "8.3",
      titre: "Levée des réserves",
      objectif: "Obtenir la levée de toutes les réserves dans les délais fixés, et constater chacune d'elles.",
      roles: [
        { acteur: "ENTREPRISES", role: "Lèvent les réserves dans le délai fixé." },
        { acteur: "MOE", role: "Constate la levée et établit le procès-verbal." },
        { acteur: "OPC", role: "Planifie les interventions, surtout en site occupé." },
        { acteur: "AMO", role: "Suit le taux de levée et alerte le maître d'ouvrage en cas de retard." },
        { acteur: "MOA", role: "Décide, en cas de carence, de faire exécuter aux frais de l'entreprise défaillante." },
      ],
      livrables: ["Tableau de levée des réserves par lot (ouvertes, levées, contestées)", "Alertes au maître d'ouvrage sur les réserves en retard"],
      outil: [
        "Suivi de chaque réserve jusqu'à sa levée, avec photo avant / après",
        "Relances automatiques avant l'échéance",
        "Pré-remplissage du procès-verbal de levée et de la décision correspondante (formulaires EXE8 et EXE9)",
      ],
      humain: ["Vérification sur site de la levée effective", "Arbitrage des réserves contestées"],
      vigilance: [
        "Une réserve non levée à l'échéance ouvre la possibilité de faire exécuter aux frais de l'entreprise, après mise en demeure.",
        "Les réserves non levées bloquent la libération des retenues de garantie : les suivre jusqu'au solde.",
      ],
      variantes: [
        { quand: { rehabilitation: true }, texte: "Site occupé : planifier les interventions avec les occupants et tracer les accès aux logements ou locaux." },
        { quand: { typologie: ["LOGEMENT"] }, texte: "Réserves à la livraison des logements : distinguer les réserves du maître d'ouvrage et celles signalées ensuite par les occupants pendant l'année de parfait achèvement." },
      ],
      textes: ["Code civil, art. 1792-6", "CCAG Travaux 2021 (réception, mesures coercitives)", "Formulaires DAJ EXE8, EXE9, EXE14"],
      statut: "brouillon",
    },
    {
      code: "8.4",
      titre: "Dossiers de fin de chantier et remise à l'exploitant",
      objectif: "Remettre à l'exploitant un ouvrage documenté : ce qui a été réellement construit, comment l'entretenir, comment intervenir dessus en sécurité.",
      roles: [
        { acteur: "ENTREPRISES", role: "Remettent les dossiers des ouvrages exécutés, notices et fiches produits." },
        { acteur: "MOE", role: "Vérifie et rassemble les dossiers des ouvrages exécutés." },
        { acteur: "SPS", role: "Remet le dossier d'intervention ultérieure sur l'ouvrage." },
        { acteur: "CT", role: "Remet son rapport final." },
        { acteur: "AMO", role: "Contrôle la complétude et organise la remise à l'exploitant." },
        { acteur: "EXPLOITANT", role: "Reçoit l'ouvrage, les dossiers et, le cas échéant, les formations." },
      ],
      livrables: ["Bordereau de remise des dossiers de fin de chantier", "Procès-verbal de remise à l'exploitant"],
      outil: [
        "Liste des documents attendus par lot, générée depuis les marchés",
        "Suivi reçu / conforme / manquant avec relances",
        "Archivage structuré des dossiers, consultable pendant toute la durée des garanties",
      ],
      humain: ["Contrôle de la cohérence entre dossiers et ouvrage réel", "Organisation de la passation avec l'exploitant"],
      vigilance: [
        "Des dossiers incomplets retardent l'exploitation et compliquent tout sinistre ultérieur.",
        "Le dossier d'intervention ultérieure est obligatoire pour les opérations soumises à coordination SPS.",
      ],
      variantes: [
        { quand: { typologie: ["BATIMENT", "BATIMENT_ERP", "LOGEMENT"] }, texte: "Déclaration attestant l'achèvement et la conformité des travaux (Cerfa 13408) lorsque l'opération relève d'un permis de construire ; vérifier les attestations réglementaires requises à l'achèvement." },
        { quand: { typologie: ["BATIMENT_ERP"] }, texte: "Autorisation d'ouverture au public après avis de la commission de sécurité." },
        { quand: { typologie: ["RESEAUX", "INFRA_LINEAIRE"] }, texte: "Remise des plans de récolement au gestionnaire du réseau ou de la voirie." },
      ],
      textes: [
        "Code du travail, art. R. 4532-95 à R. 4532-98 (dossier d'intervention ultérieure sur l'ouvrage)",
        "Code de l'urbanisme, art. R. 462-1 à R. 462-10 (achèvement des travaux)",
        "Cerfa 13408",
      ],
      statut: "brouillon",
    },
    {
      code: "8.5",
      titre: "Décomptes et solde des marchés",
      objectif: "Arrêter le montant définitif de chaque marché sans laisser de réclamation latente.",
      roles: [
        { acteur: "ENTREPRISES", role: "Remettent leur projet de décompte final dans le délai du CCAG." },
        { acteur: "MOE", role: "Établit le décompte final." },
        { acteur: "AMO", role: "Vérifie les décomptes (pénalités, révisions, modifications, retenues) et prépare le décompte général pour le maître d'ouvrage." },
        { acteur: "MOA", role: "Arrête et notifie le décompte général ; paie le solde." },
      ],
      livrables: ["Note de vérification des décomptes par marché", "Projet de décompte général soumis au maître d'ouvrage", "Bilan financier de l'opération"],
      outil: [
        "Rapprochement automatique : montant initial, modifications, révisions, pénalités, acomptes versés",
        "Échéancier des délais de décompte avec alertes",
        "Contrôle de mise à jour des données essentielles du marché publiées par l'acheteur",
      ],
      humain: ["Examen des réclamations", "Recommandation au maître d'ouvrage sur leur traitement"],
      vigilance: [
        "Le décompte général signé sans réserve par l'entreprise devient définitif : toute réclamation doit avoir été traitée avant.",
        "Les délais de notification du décompte général sont stricts ; leur dépassement affaiblit la position du maître d'ouvrage.",
        "Ne pas oublier le solde des marchés de maîtrise d'œuvre et de prestations intellectuelles.",
      ],
      variantes: [
        { quand: { montage: ["MARCHE_PRIVE"] }, texte: "Mémoire définitif et règlement selon le contrat ; retenue de garantie encadrée par la loi du 16 juillet 1971." },
      ],
      textes: [
        "CCAG Travaux 2021 (décompte final, décompte général, différends)",
        "Code de la commande publique, art. R. 2191-32 à R. 2191-44 (garanties)",
        "Arrêté du 22 décembre 2022 relatif aux données essentielles des marchés publics",
      ],
      statut: "brouillon",
    },
    {
      code: "8.6",
      titre: "Garantie de parfait achèvement et suivi des garanties",
      objectif: "Faire jouer les garanties pendant qu'elles courent, puis libérer les sûretés à bon droit.",
      roles: [
        { acteur: "EXPLOITANT", role: "Signale les désordres apparus après réception." },
        { acteur: "AMO", role: "Qualifie chaque désordre au regard des garanties, notifie l'entreprise concernée, suit la reprise." },
        { acteur: "MOE", role: "Assiste le maître d'ouvrage pendant l'année de parfait achèvement si sa mission le prévoit." },
        { acteur: "MOA", role: "Notifie les désordres, déclare les sinistres, décide de la libération des retenues." },
      ],
      livrables: ["Registre des désordres et de leur traitement", "Avis sur la libération des retenues de garantie ou des cautions"],
      outil: [
        "Registre des désordres rattaché au lot et à l'entreprise responsable",
        "Échéancier des garanties calculé depuis la date de réception, avec alertes avant expiration",
      ],
      humain: ["Qualification technique des désordres", "Relation avec l'exploitant et les entreprises"],
      vigilance: [
        "Un désordre signalé après l'expiration de la garantie de parfait achèvement ne peut plus être traité à ce titre.",
        "Pour un désordre de nature décennale, déclarer à l'assureur dommages-ouvrage lorsqu'il en existe une.",
        "Retenue de garantie : libération à l'expiration du délai de garantie sauf opposition motivée.",
      ],
      variantes: [],
      textes: [
        "Code civil, art. 1792, 1792-3, 1792-6",
        "Loi n° 71-584 du 16 juillet 1971 (retenue de garantie)",
        "Code de la commande publique, art. R. 2191-32 à R. 2191-44",
        "Code des assurances, art. L. 242-1 (assurance dommages-ouvrage)",
      ],
      statut: "brouillon",
    },
    {
      code: "8.7",
      titre: "Clôture de l'opération et retour d'expérience",
      objectif: "Clore proprement l'opération et enrichir la mémoire du cabinet.",
      roles: [
        { acteur: "AMO", role: "Établit le bilan de l'opération et organise le retour d'expérience." },
        { acteur: "OPC", role: "Analyse les écarts de planning et leurs causes." },
        { acteur: "MOA", role: "Reçoit le bilan ; décide de l'archivage." },
      ],
      livrables: ["Bilan de l'opération : coûts, délais, qualité, réclamations", "Fiche de retour d'expérience interne Archiaccess"],
      outil: [
        "Bilan pré-rempli depuis les données du projet : écarts de coût et de délai, modifications, réserves, réclamations",
        "Ratios de coûts par typologie, réutilisables sur les opérations suivantes",
        "Archivage de l'espace projet en lecture seule",
      ],
      humain: ["Analyse des causes et leçons tirées", "Échange de clôture avec le maître d'ouvrage"],
      vigilance: [
        "Conserver les pièces pendant toute la durée des responsabilités (dix ans après réception au moins).",
        "Anonymiser ce qui doit l'être avant de réutiliser un retour d'expérience sur une autre opération.",
      ],
      variantes: [],
      textes: ["Code civil, art. 1792-4-1 (durée de la responsabilité décennale)"],
      statut: "brouillon",
    },
  ],
}
